### ISSUE TITLE
Edencom ships ?

### ISSUE THREAD

**Issue by LeonMskRu** [mjibson/fittin.gs#5]
Hi !

Plz add
https://zkillboard.com/ship/54731/losses/
https://zkillboard.com/ship/54732/losses/
https://zkillboard.com/ship/54733/losses/

-- 
Thanks

**Comment by mjibson** [comment]
Done! Example: https://fittin.gs/fit/85172110

Thanks for the request.

**Comment by mjibson** [comment]
Since these just got added, search on new items won't work until new stuff starts to come in.
