### ISSUE TITLE
New Edencom ships == loading ?

### ISSUE THREAD

**Issue by LeonMskRu** [mjibson/fittin.gs#6]
Hi!

Thanks for add this ships.
Only many trying view this results https://i.imgur.com/XfaIIeb.png

And some RANDOM times show fits/kills

https://fittin.gs/?ship=54731
https://fittin.gs/?ship=54732
https://fittin.gs/?ship=54733

p.s. Chromium browser + Mozilla Firefox
F5 for reload

p.p.s. try open https://fittings-5anqu7dwna-uc.a.run.app/api/Fits?ship=54731
too too too LONG time and white screen

**Comment by LeonMskRu** [comment]
https://fittin.gs open last kill in few seconds

**Comment by mjibson** [comment]
Thanks for the report. This has been fixed in 83504fbc1ca062cf21eeb8352382e7bdb6b7bf1c and things are way faster now.
